# Generated by Django 6.1 on 2026-08-16 17:22

import django.db.models.deletion
from django.db import migrations, models



def set_initial_rank(apps, schema_editor):
    PlayerProfile = apps.get_model('users_app', 'PlayerProfile')
    Rank = apps.get_model('ranks_app', 'Rank')

    first_rank = Rank.objects.order_by('order').first()

    PlayerProfile.objects.filter(
        current_rank__isnull=True
    ).update(current_rank=first_rank)


class Migration(migrations.Migration):

    dependencies = [
        ('ranks_app', '0002_create_ranks'),
        ('users_app', '0002_playerprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerprofile',
            name='current_rank',
            field=models.ForeignKey(
                on_delete=models.PROTECT,
                related_name='players',
                to='ranks_app.rank',
                null=True,
            ),
        ),
        migrations.RunPython(set_initial_rank),
    ]
