# Generated by Django 6.1 on 2026-08-16 17:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ranks_app', '0002_create_ranks'),
        ('users_app', '0003_playerprofile_current_rank'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playerprofile',
            name='current_rank',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='players', to='ranks_app.rank'),
        ),
    ]
